---
title: "object of the type 'closure' is not subsettable"
author: 
- Martín Paladino^[mpaladino@mora.edu.mx]
date: Actualizado el `r format(Sys.time(), "%d/%m/%Y")`
output: 
  html_document: 
    theme: united
---

Esta es la página que acompaña al repositorio homónimo. Incluye las salidas en .html de las guías de manejo de datos, gráficos y modelado en R.  
Cuando aprenda a usar Jekyll esto será un blog, por ahora es web 1.0. Si quiere hacer algún comentario debe tener una cuenta de GitHub y abrir un issue o pull request en directamente en el [repositorio](https://github.com/martinpaladino/martinpaladino.github.io).  
El diseño es austero para acompañar a la época.^[Al diseñador le indexaron el pago en UMA "para recuperar el espíritu original y la verdadera función social del salario mínimo."]

Mis caprichos: 

1. *Investigación reproducible.* Porque hay cosas mejores que hacer en la vida que copiar la salida de STATA, pegar en Excel, formatear, copiar, pegar a Word, ver si entra en una página, descubrir que no, volver a formatear en Excel, pegar en Word, revisar y repetir el procedimiento cuando me dí cuenta que los códigos de una variable estaban mal. 

2. *Programación funcional e inmutabilidad de los datos.* Porque hay cosas mejores para hacer en la vida que buscar la línea de código exacta que los corrompió. 

3. *La gramática de lo gráficos.* Porque hay cosas mejores que hacer en la vida que mirar piecharts en 3D.  

4. *Análisis de datos categóricos.* Porque soy sociólogo. 

#Guías de  R.

##[Investigación reproducible con R](https://martinpaladino.github.io/programacion_funcional.html)

- Investigación reproducible. 
    - Definición. 
    - Cadena de software libre para investigación reproducible. 
    
- Conceptos de la programación funcional aplicables a la investigación reproducible. 
    - Inmutabilidad de los datos. 
    - Transparencia referencial. 
    - Funciones puras. 
- CODA

##[Manipulación de datos con dplyr](https://martinpaladino.github.io/manipulacion_de_datos_con_r_dplyr_y_tidyr.html)

Resumida en cuatro operaciones:

- Extraer subconjuntos de datos. 
    - Selección de columnas. 
    - Filtrado de filas.  
- Transformarlos. 
    - Recodificaciónd de variables categóricas. 
    - Operaciones aritméticas sobre variables numéricas.
- Obtener sumarios. 
    - Para el conjunto de los datos.
    - Por grupos.  
-Unir múltiples bases de datos. 

##[Gráficos con R y ggplot](https://martinpaladino.github.io/graficos_con_r_y_ggplot.html)

- Desde la gramática de los gráficos hasta gráficos multivaridos. 
    - Definición concetual de gráficos y sus elementos. 
- Gráficos básicos por tipos: columnas, línea, dispersión.
- Gráficos multivariados.
    - Con claves de color o símbolos.
    - Multipanel.
- Control del aspecto estético de los gráficos. 
    - Con estilos visuales predefinidos. 
    - Personalizado. 
- Gráficos exploratorios con sintaxis simplificada. 
  


#Ejercicios. 

##[Series de tiempo con R](https://martinpaladino.github.io/series_de_tiempo_con_R.html)

Le viene incluyendo todo lo que es...

- Importación de datos con fechas. 
    - Conversión de caracteres a fechas con `lubridate()`
- Manipulación de datos en formato de fecha en R.
    - Sumarios de series de tiempo con periodización. 
    - Operaciones aritméticas con fechas. 
- Gráficos de series de tiempo. 
- Descomposición de series de tiempo. 
    - Gráficos de descomposición de series de tiempo. 
    
##[Agregar un nivel de agrupamiento a una base de datos existente](https://martinpaladino.github.io/Datos_jerarquicos.html)

Ejercicio práctico de manipulación de datos en R. 

Le viene incluyendo todo lo que es... 

- Definición de datos jerárquicos. 
- Problema práctico: agregar una nueva jeraquía a datos existentes. 
- Solución del problema con R. 
    - Con un bucle.
    - Con una función vectorizada. 
    - Con un join de bases de datos. 
- Benchmarks. 

##[Cartografía con R. (beta)](https://martinpaladino.github.io/Mapas_con_R.html)

Cartografía digital en R. 

Le viene incluyendo todo lo que es...

- Sistemas de coordenadas. 
    - Incluyendo el sistema de coordenadas estándar del INEGI.
- Importación de shapefiles. 
    - Objetos SPDF.
- Importanción de rutas desde un teléfono celular.

- Mapas coropléticos con ggplot(). 
    - Con geom_map()
    - Y geom_polygon()
- Mapas coropléticos de México con mxmaps. 
- Importación de capas raster desde GoogleMaps, Stamen y OpenStreetMap
